name: webkitgtk-6-gnome-2204-sdk # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Web content engine for GTK(SDK) # 79 char long summary
description: |
  SDK snap for Webkitgtk-6.0+, used with gnome-42-2204 and core22.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  webkitgtk-6-gnome-2204-sdk:
    #source: https://webkitgtk.org/releases/webkitgtk-2.40.1.tar.xz
    source: https://github.com/WebKit/WebKit.git
    source-tag: webkitgtk-2.40.1
    plugin: cmake
    cmake-parameters:
      - -DPORT=GTK
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_INSTALL_LIBDIR=lib/$CRAFT_ARCH_TRIPLET
      - -DCMAKE_INSTALL_LIBEXECDIR=lib/$CRAFT_ARCH_TRIPLET
      - -DCMAKE_SKIP_RPATH=ON
      - -DUSE_AVIF=ON
      - -DUSE_GTK4=ON
      - -DENABLE_JOURNALD_LOG=OFF
      - -DENABLE_DOCUMENTATION=OFF
      - -DENABLE_MINIBROWSER=ON
    build-packages:
      - bubblewrap
      - gettext
      - gperf
      - icu-devtools
      - libavif-dev
      - libcairo2-dev
      - libcurl4-gnutls-dev
      - libdav1d-dev
      - libenchant-2-dev
      - libepoxy-dev
      - libfreetype-dev
      - libgcrypt20-dev
      - libghc-text-icu-dev
      - libghc-text-icu-prof
      - libgav1-dev
      - libglx-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgtk-4-dev
      - libharfbuzz-dev
      - libhyphen-dev
      - libicu-dev
      - libicu-le-hb-dev
      - liblcms2-dev
      - libmanette-0.2-dev
      - libnghttp2-dev
      - libopenjp2-7-dev
      - libopengl-dev
      - libpng-dev
      - libsoup-3.0-dev
      - libsecret-1-dev
      - libseccomp-dev
      - libsqlite3-dev
      - libtasn1-6-dev
      - libwebp-dev
      - libwpe-1.0-dev
      - libwpebackend-fdo-1.0-dev
      - libwoff-dev
      - libxcomposite-dev
      - libxdamage-dev
      - libxrender-dev
      - libxslt1-dev
      - libxt-dev
      - ruby-all-dev
      - unifdef
      - xdg-dbus-proxy
      
  deps:
    plugin: nil
    after: [webkitgtk-6-gnome-2204-sdk]
    override-prime: |
      craftctl default
      for PC in $(find . -path "*/pkgconfig/*.pc")
      do
         sed -i '1cprefix=/snap/webkitgtk-6-gnome-2204-sdk/current/usr' $PC
         sed -i 's#libdir=/usr/lib#libdir=${exec_prefix}/lib#' $PC
      done   
    stage-packages:
      - bubblewrap
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - libabsl20210324
      - libaom3
      - libatomic1
      - libavif13
      - libdav1d5
      - libelf-dev
      - libenchant-2-2
      - libgav1-0
      - libwoff1  
      - libwpe-1.0-1
      - libwpebackend-fdo-1.0-1
      - libyuv0